### ISSUE TITLE
Web page applications not working

### ISSUE THREAD

**Issue by itamayo** [kixelated/moq-js#122]
I'm not sure if the issue is due to the new fork or the circumstances with the IETF, but it seems that the demos on the official website are not functioning properly. Is this related to those circumstances, or am I doing something wrong?

**Comment by kixelated** [comment]
It's working again, thanks!

I don't quite have automatic deployments set up and introduced a breaking change.

**Comment by itamayo** [comment]
Thank you for your availability. I’ve tested it, and it seems that even though the connection is working well on the WebTransport level, nothing actually arrives—at least in my case.
