### ISSUE TITLE
WebTransportError: Connection lost

### ISSUE THREAD

**Issue by junkai0531** [kixelated/moq-js#48]
I run moq-cert, moq-relay, moq-pub, moq-js on ubuntu 22.04
then I access [https://localhost:4321/watch/<name>/?server=localhost:4443](https://localhost:4321/watch/%3Cname%3E/?server=localhost:4443) with chrome 117.0.5938.149
no network error reported in terminal, but I failed to play the video
the website shows this: WebTransportError: Connection lost
can I get some help?

**Comment by kixelated** [comment]
You need to specify the broadcast name in the URL. moq-pub prints it out:

```
https://localhost:4321/watch/name_from_moq-pub/?server=localhost:4443
```

**Comment by kixelated** [comment]
(TODO update moq-pub to print out the correct URL)

**Comment by junkai0531** [comment]
my problem solved, thanks a lot!
