### ISSUE TITLE
Catalog.isVideoTrack expects frame_rate

### ISSUE THREAD

**Issue by zafergurel** [kixelated/moq-js#79]
In moq-pub, it's possible that the bitrate is not passed in the track data:
https://github.com/kixelated/moq-rs/blob/75e7dc03bfc0e64fe243742478bd755b399045a2/moq-pub/src/media.rs#L188

I'm using dev/pub to test the player and changing it to try out something. I needed to use Catalog.isVideoTrack but it expects a video track to have frame_rate:
https://github.com/kixelated/moq-js/blob/e76206fc30b2ccd4a467f3516a43027b347b387b/lib/media/catalog/index.ts#L115

I think we need to remove this check.

**Comment by kixelated** [comment]
Makes sense.
